name: ðŸ“š Documentation issue
description: Suggest an enhancement/fix to documentation
title: "DocFix: "
labels:
    - "issue: documentation ðŸ“ƒ"
    - "status: backlog ðŸ“š"
    - "priority: low âšª"
body:
    - type: markdown
      attributes:
          value: |
              - [x] Documentation
                Thank you for helping us make documentation better! Use the sections below to submit a issue.
              - All help is welcome - we want to fix them!âš’ï¸
              - This repo is maintained by volunteers. Please be courteous and patient. ðŸ™‚
              - Remember to include sufficient details and context.
              - If you have multiple documentation suggestions to report, please submit them as separate issues.
              - We accept pull requests. If you know how to fix it - go ahead!

    - type: dropdown
      id: action
      attributes:
          label: âš’ï¸ Do you want to add, repair or remove documentation?
          options:
              - "Add"
              - "Repair"
              - "Remove"

    - type: input
      id: topic
      validations:
          required: true
      attributes:
          label: ðŸ“„ Where is the documentation change needed?
          description: name of the modele > function > etc where the change is needed

    - type: markdown
      attributes:
          value: Provide a clear & concise description of why the documentation change is needed.

    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: ðŸ–Šï¸ Please describe the bug in detail
          description: Please provide the issue being faced along with the context
          value: |
              the documentation in
              {module > function > etc} needs to be
              {added/remove/updated} as the code for it is {changed/removed}
              [and needs to be updated to {new documentation}]

    - type: textarea
      validations:
          required: false
      attributes:
          label: ðŸ˜Š Any other notes you want to add
