name: "🧱➛⚙️ setup project"

on:
    workflow_call:
        inputs:
            os:
                type: string
                description: "the operating system/s the jobs need to be set up with"
                default: "ubuntu-latest"
            node:
                type: string
                description: "the version/s node needs to be set up with"
                default: "16"

jobs:
    # set up the current branch
    checkout:
        runs-on: ${{ inputs.os }}
        steps:
            - name: "setup repository branch ${{ github.ref }}"
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Save repository's content as artifact"
              uses: actions/upload-artifact@v3
              with:
                  name: "${{ github.workflow }}-${{ inputs.os }}_${{ inputs.node }}"
                  path: ${{ github.workspace }}
