name: "🧱➛🔍 audit vunerabilities"

on:
    workflow_call:
        inputs:
            os:
                type: string
                description: "the operating system/s the jobs need to be set up with"
                default: "ubuntu-latest"
            node:
                type: string
                description: "the node version/s the jobs need to be set up with"
                default: "16"
        secrets:
            SNYK_TOKEN:
                required: true

jobs:
    # scan for vunerabilities in the code
    code:
        name: "checking code vunerabilities with snyk"
        runs-on: ${{ inputs.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: code test
                  args: --severity-threshold=low --all-projects --org=officialk ./src/

    # scan for vunerabilities in the package dependencies
    package:
        name: "checking package vunerabilities"
        runs-on: ${{ inputs.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - uses: DerYeger/yarn-setup-action@master
              with:
                  node-version: ${{ inputs.node }}
            - run: yarn run check:audit

    #     # scan for vunerabilities/expirations of license/s
    license:
        name: "checking license vunerabilities"
        runs-on: ${{ inputs.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: test
